spring:
  application:
    name: eureka
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
#    service-url:
#      defaultZone: http://localhost:8080/eureka
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
